name: Commits Range Action
description: Gets a range of commits and their related pull requests
author: Arik Maor
inputs:
  github_token:
    required: true
    description: Token for github requests.
  base_revision:
    required: true
    description: Base revision (commit) of the range.
  head_revision:
    required: false
    description: Head revision (commit) of the range (defaults to the head commit of the workflow context).
outputs:
  result:
    description: JSON object describing the commits in pull requests in base and head branches

runs:
  using: node16
  main: dist/index.js
