name: Commits Range Action
description: Gets a range of commits and their related pull requests
author: Arik Maor
inputs:
  base_revision:
    required: true
    description: Base revision (commit) of the range.
  head_revision:
    required: false
    description: Head revision (commit) of the range (defaults to the head commit of the workflow context).
outputs:
  new_commits:
    description: Commits included in the head revision that aren't included in the base revision
  removed_commits:
    description: Commits include in the base revision that aren't included in the head revision
  new_prs:
    description: Pull requests related to new commits
  removed_prs:
    description: Pull requests related to removed commits

runs:
  using: node16
  main: dist/index.js
