name: Commits Range Action
description: Gets a range of commits and their related pull requests
author: Arik Maor
inputs:
  github_token:
    required: true
    description: Token for github requests.
  base_revision:
    required: false
    description: Base revision (commit) of the range (if empty or not found, empty lists will be returned).
  head_revision:
    required: false
    description: Head revision (commit) of the range (defaults to the head commit of the workflow context).
  include_body:
    required: false
    description: Fetch the entire body/description of pull requests
outputs:
  result:
    description: JSON object describing the commits in pull requests in base and head branches

runs:
  using: node16
  main: dist/index.js

branding:
  icon: git-pull-request
  color: purple
